"""add indexes and onupdate to timestamps

Revision ID: 253d9e496582
Revises: dfe21e7f7b3f
Create Date: 2026-02-21 04:14:59.412631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '253d9e496582'
down_revision: Union[str, Sequence[str], None] = 'dfe21e7f7b3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cases_assignee'), 'cases', ['assignee'], unique=False)
    op.create_index(op.f('ix_cases_current_status'), 'cases', ['current_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cases_current_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_assignee'), table_name='cases')
    # ### end Alembic commands ###
